// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBErijvCm5Os1gEKVKxFbgxfBpyWyTkt4Q',
    appId: '1:416748588922:web:f8c2eac4f7620300ebd0c3',
    messagingSenderId: '416748588922',
    projectId: 'habit-tracker-bd8d9',
    authDomain: 'habit-tracker-bd8d9.firebaseapp.com',
    storageBucket: 'habit-tracker-bd8d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf9GFwWqqsKUZBOKd_Tijn1dETak4UuYk',
    appId: '1:416748588922:android:f9e9e4fdcf963f61ebd0c3',
    messagingSenderId: '416748588922',
    projectId: 'habit-tracker-bd8d9',
    storageBucket: 'habit-tracker-bd8d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm-hXEJna93VLE1OFi-zXk24qgildmeJo',
    appId: '1:416748588922:ios:89e227b6ca5501feebd0c3',
    messagingSenderId: '416748588922',
    projectId: 'habit-tracker-bd8d9',
    storageBucket: 'habit-tracker-bd8d9.appspot.com',
    iosBundleId: 'com.example.habit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm-hXEJna93VLE1OFi-zXk24qgildmeJo',
    appId: '1:416748588922:ios:c6e764735584397eebd0c3',
    messagingSenderId: '416748588922',
    projectId: 'habit-tracker-bd8d9',
    storageBucket: 'habit-tracker-bd8d9.appspot.com',
    iosBundleId: 'com.example.habit.RunnerTests',
  );
}
